### ISSUE TITLE
Criação da página sobre

### ISSUE THREAD

**Issue by wbrasil10** [wesllyakatsuka/github-master#3]
Weslly, poderia criar uma página de sobre? Obrigado.

**Comment by wesllyakatsuka** [comment]
Sim, página em produção.

**Comment by wbrasil10** [comment]
Obrigado, estou aguardando!


Atenciosamente,
Weslly Akatuka de Oliveira
wesllyakatsuka@hotmail.com<http://hotmail.com>
(11) 96981-7979
________________________________
De: Weslly <notifications@github.com>
Enviado: sábado, 8 de setembro de 2018 12:11:09
Para: wesllyakatsuka/github-master
Cc: Weslly; Author
Assunto: Re: [wesllyakatsuka/github-master] Criação da página sobre (#3)


Sim, página em produção.
